{
 "title": "#1",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "query0",
    "query": {
     "query": "label_values(pg_database_size_bytes, datname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Update Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(5, rate(pg_stat_user_tables_n_tup_upd[5m]))\r\n",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "pg_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Insert Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_n_tup_ins[1m])",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Active users count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_stat_activity_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tables Access",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_user_tables_seq_scan) by (relname)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Size(Bytes)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"postgres\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_user_tables_n_tup_ins)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of tables and rows",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pg_stat_user_tables_n_live_tup)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(pg_stat_user_tables_n_live_tup)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buffer Cache hit ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Read Operations Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_read[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}