{
 "title": " Node Exporter (System Metrics)",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "query0",
    "query": {
     "query": "label_values(node_network_receive_bytes_total{device=~\"$query0\"},device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System Uptime (hours)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_time_seconds - node_boot_time_seconds) / 3600\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming Traffic ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[1m]) * 8 / 1000 / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Processes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_procs_running", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes / 1024 / 1024 / 1024\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_memory_MemAvailable_bytes / 1024 / 1024 / 1024\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / 1024 / 1024 / 1024\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk I/O - read & write (bytes/sec)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=~\"$query0\"}[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(node_disk_written_bytes_total[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk free",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load Average (1, 5, 15 min)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load1\r\n", "legendFormat": "__auto" },
    { "expr": "node_load5\r\n", "legendFormat": "__auto" },
    { "expr": "node_load15\r\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage per core",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}