{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "city",
    "query": {
     "query": "label_values(weather_temperature_celsius, city)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overcast",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_cloudiness_percent{city=~\"$city\"}",
     "legendFormat": "{{city}}"
    }
   ]
  },
  {
   "title": "Feel like Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_feels_like_celsius{city=~\"$city\"}",
     "legendFormat": "{{city}}"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "weather_sunrise_timestamp{city=~\"$city\"}",
     "legendFormat": "{{city}}"
    }
   ]
  },
  {
   "title": "Cloudiness percent",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "weather_cloudiness_percent{city=~\"$city\"}",
     "legendFormat": "{{city}}"
    }
   ]
  },
  {
   "title": "Windspeed(m/s)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_wind_speed_ms{city=~\"$city\"}",
     "legendFormat": "{{city}}"
    }
   ]
  },
  {
   "title": "Humidity percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "weather_humidity_percent{city=~\"$city\"}",
     "legendFormat": "{{city}}"
    }
   ]
  },
  {
   "title": "Wind direction(degree)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "weather_wind_direction_deg{city=~\"$city\"}",
     "legendFormat": "{{city}}"
    }
   ]
  },
  {
   "title": "Visibility(km)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_visibility_meters{city=~\"$city\"} / 1000",
     "legendFormat": "{{city}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "weather_temperature_celsius{city=~\"$city\"}\r\n",
     "legendFormat": "{{city}}"
    }
   ]
  },
  {
   "title": "Atmospheric pressure",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "weather_pressure_hpa{city=~\"$city\"}",
     "legendFormat": "{{city}}"
    }
   ]
  }
 ]
}